### ISSUE TITLE
Remove tiles

### ISSUE THREAD

**Issue by Brutuss** [robgeerts/Dashticz#11]
With the new version of Dashticz (0.63) it is possible the remove some tiles because al switches and scenes are visible now.

When you select the pencil and then the tile you want to remove you get a little popup. 
After that you can select hide tile and then save. 

After saving, the tile is still available even when I refresh the page.

**Comment by robgeerts** [comment]
I didn't have this bug but I've tried something ;)

I just commit a new version.
Could you test if the problem still occurs?

**Comment by robgeerts** [comment]
After I had tested this issue with Brutuss I have found the problem.
Just commited a possible fix.
