### ISSUE TITLE
Domoticz Room support

### ISSUE THREAD

**Issue by gooilander** [robgeerts/Dashticz#19]
Thanx for the nice work!

Feature request: Support the 'Room' feature from the domoticz UI within Dashticz somehow with a (nice) additional navigation level. In whatever acceptible shape (tabs, foldouts f.e.). 

Rationale: For larger setups (i have in total >20 switches, >20 thermometers and >20 utility sensors), a straightforward single screen results in too much scrolling, is quite unusable on a smartphone and lacks the 'natural' order of floors and rooms in the house. Since this ordering should already be done in Domoticz itself, it seems superfluous to realize this trough manual re-ordering in the dashticz UI.

**Comment by robgeerts** [comment]
Hi 'gooilander', how did you setup floorplans? Did you create a roomplan with multiple switches and added them to a floorplan? Would you like to choose a floorplan or roomplan in Dashticz?

**Comment by robgeerts** [comment]
In the latest version you can select a floorplan in the dropdown at the top of the dashboard... note: it's beta-functionality

**Comment by gooilander** [comment]
Hi Rob,

Thanx a lot for the swift beta implementation - and can confirm that it works nicely!. Also great that you added the camera's in your latest version - I can confirm that the screenshots are working but that the mini screenshots are delaying the buildup of the additional modules - in my case with 4 cameras (Foscam and Panasonic) for about 5 seconds.

Now, As an answer to your intial first and second question: My 'Hierarchy' is as follows: I have 

a) plans that follow physical rooms: Living Room, Kitchen, Utility Room, Bedroom 1-3, Bathroom, Hallway, Attic, Garden. All switches and sensors that have a physical location are mapped to the respective plan.
b) plans that follow logical functions: Multimedia, Home Network

I have 3 floorplans that contain the physical plans mentioned above: Ground Floor (Garden, Living Room, Kitchen, Halway), First Floor(Bedrooms etc.), Attic (etc). I am considering adding a virtual floorplan for the logical functions since they tend to clutter the physical map.

As to your third question, for my sitiuation, choosing a floorplan like you did in this beta feels as the more natural approach since it follows the structure of the home and is not too granular. 

I am not a GUI designer nor bootstrap expert, but a direct floorplan selection instead of the 2 click/tap dropdown would be appreciated. I disliked this a dropdown already a lot in the standard Domoticz GIU.

**Comment by robgeerts** [comment]
Thanks for your feedback!
I will try to remove the delay for the additional modules.

I'm not a GUI designer either but I didn't like the floorplan-images (although, not the example ones in Domoticz), thats why I first created the regular dropdowns. I will take a look at this as soon as possible.

But, I'm very thrilled to hear the basics are working correctly!

**Comment by robgeerts** [comment]
I will close this issue for now, because it's working, could you please open a ticket for the GUI changes if needed, as already mentioned: I'll will change this anyway so it will be a bit nicer.
