### ISSUE TITLE
Add support for Plex?

### ISSUE THREAD

**Issue by mbnn** [robgeerts/Dashticz#2]
Hello,

Would it be possible to add support for Plex (Home Theater)? I think it will work with the same data as XBMC so it should be rather easy.

**Comment by robgeerts** [comment]
Thanks for the suggestion!
I will install Plex on my NAS (Synology in my case) so I can take a look at the possibilities!

**Comment by robgeerts** [comment]
I just started Plex integration, currently I'm only showing if something is playing on the Plex Media Server.

![dashticz](https://cloud.githubusercontent.com/assets/5435581/6314639/d9ca706e-b9e6-11e4-962b-cf10db68c6a2.jpg)

**Comment by robgeerts** [comment]
You can download version 0.80 with support for this block, but remember, to use this function, you have to install Dashticz on a webserver with PHP-support inside your network.
