### ISSUE TITLE
Mobile: Menu is not showing correctly

### ISSUE THREAD

**Issue by scns** [robgeerts/Dashticz#26]
When i look on my mobile (iphone 5s) the menu bar on the top of the page takes almost the half of the page. 

See screenshot
![img_2690](https://cloud.githubusercontent.com/assets/7148071/7190707/4b0a66aa-e488-11e4-8eb0-66e70e38fdad.jpg)

Is there maybe an option to create an responsive menu (when shown on smaller screens, convert to a pulldown menu). 

This menu makes this theme almost unusable on smartphones.

**Comment by robgeerts** [comment]
I have changed this in the latest version. Could you give this a try?

**Comment by scns** [comment]
Problem solved! Tnx!

![img_2786](https://cloud.githubusercontent.com/assets/7148071/7666651/133331e0-fbed-11e4-96ce-b1a94603fabd.jpg)
