### ISSUE TITLE
Plaatjesdump link werkt niet

### ISSUE THREAD

**Issue by Dylantje** [robgeerts/Dashticz#28]
Ik zou hem wel willen zien.
Voordat ik hem installeer.

En misschien de wili op domoticz iets uitgebreider maken?

**Comment by robgeerts** [comment]
Screenshots zijn aangepast!
De wiki op Domoticz.com is express verwijderd, er staat alleen nog maar een link hier naartoe.
Dit om te voorkomen dat informatie op 2 plaatsen aangepast moet worden.
